name: example
description: A new Flutter project.
version: 0.2.0

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # seatsio: ^0.1.1
  seatsio:
    path: ../
  built_collection: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
