name: seatsio
description: -> 
  This is the Flutter version of seatsio SDK.
  It helps you integrate seating charts into Flutter apps.
repository: https://github.com/SongJiaqiang/seatsio-flutter
version: 0.4.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  built_collection: ^5.1.0
  built_value: ^8.7.0
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  built_value_generator: ^8.7.0

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
